Use cacheable Rust build layers in the container, to speed up builds.

diff --git a/rollout-dashboard/Dockerfile b/rollout-dashboard/Dockerfile
--- a/rollout-dashboard/Dockerfile
+++ b/rollout-dashboard/Dockerfile
@@ -1,8 +1,12 @@
 FROM docker.io/rust:1.80-bookworm as rust
 WORKDIR /usr/src
-COPY server/Cargo.toml server/Cargo.lock ./
+RUN cargo new rollout-dashboard
+COPY server/Cargo.toml server/Cargo.lock ./rollout-dashboard/
+WORKDIR /usr/src/rollout-dashboard
+RUN cargo build --release ; rm -rf src ; echo "This step is expected to fail, but it creates a layer that is cacheable." >&2
 COPY server/src ./src/
-RUN cargo install --path .
+RUN cargo build --release && \
+    mv target/release/rollout-dashboard .
 
 FROM docker.io/node:alpine as node
 WORKDIR /
@@ -13,9 +17,9 @@ RUN npm install && npm run build
 
 FROM docker.io/debian:bookworm
 WORKDIR /
-RUN apt-get update && apt install -y openssl ca-certificates
-COPY --from=rust /usr/local/cargo/bin/rollout-dashboard /rollout-dashboard
+COPY --from=rust /usr/src/rollout-dashboard/rollout-dashboard /rollout-dashboard
 COPY --from=node /dist /static
+RUN apt-get update && apt install -y openssl ca-certificates
 
 EXPOSE 4174
 ENV FRONTEND_STATIC_DIR=static
